test/unknattr.hsc (4,13): Warning 11: unknown tag <unknown-tag>
test/unknattr.hsc (5,20): Error 85: unknown attribute hugo for tag <SEPP>
test/unknattr.hsc (5,29): Error 85: unknown attribute susi for tag <SEPP>
test/unknattr.hsc (6,8): Warning 84: unknown attribute resi for tag <B>
test/unknattr.hsc (6,13): Warning 84: unknown attribute hugo for tag <B>
test/unknattr.hsc (7,21): Error 20: unknown attribute hugo
test/unknattr.hsc (8,21): Error 20: unknown attribute undefined-attr
test/unknattr.hsc (8,29): Error 30: unmatched `>'
