/* C headerfile generated by RevUp 1.4 */

#define VERSION		0
#define REVISION	9
#define BETA	3
#define DATE	"9.3.96"
#define VERS	"LoadHscPrefs 0.9 BETA 3"
#define VSTRING	"LoadHscPrefs 0.9 BETA 3 (9.3.96)\r\n"
#define VERSTAG	"\0$VER: LoadHscPrefs 0.9 BETA 3 (9.3.96)"
#define TIME	"15:31:34"
#define PRGNAME	"LoadHscPrefs"
#define BASENAME	"LOADHSCPREFS"
#define VSTR	"LoadHscPrefs 0.9 BETA 3 (9.3.96)"
#define USER	"Thomas.Aglassinger"
#define HOST	"giga.or.at"
