/* C headerfile generated by RevUp 1.4 */

#define VERSION		1
#define REVISION	1
#define DATE	"1.8.96"
#define VERS	"hscdepp 1.1"
#define VSTRING	"hscdepp 1.1 (1.8.96)\r\n"
#define VERSTAG	"\0$VER: hscdepp 1.1 (1.8.96)"
#define TIME	"01:30:09"
#define PRGNAME	"hscdepp"
#define BASENAME	"HSCDEPP"
#define VSTR	"hscdepp 1.1 (1.8.96)"
#define USER	"Thomas.Aglassinger"
#define HOST	"giga.or.at"
