/* C headerfile generated by RevUp 1.4 */

#define VERSION		1
#define REVISION	2
#define DATE	"29.10.96"
#define VERS	"hscdepp 1.2"
#define VSTRING	"hscdepp 1.2 (29.10.96)\r\n"
#define VERSTAG	"\0$VER: hscdepp 1.2 (29.10.96)"
#define TIME	"13:35:40"
#define PRGNAME	"hscdepp"
#define BASENAME	"HSCDEPP"
#define VSTR	"hscdepp 1.2 (29.10.96)"
#define USER	"Thomas.Aglassinger"
#define HOST	"giga.or.at"
