/*
 * This source code is part of hsc, a html-preprocessor,
 * Copyright (C) 1995-1997  Thomas Aglassinger
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */
/* C headerfile generated by RevUp 1.4 */

#define VERSION		1
#define REVISION	1
#define DATE	"8.5.97"
#define VERS	"hscpitt 1.1"
#define VSTRING	"hscpitt 1.1 (8.5.97)\r\n"
#define VERSTAG	"\0$VER: hscpitt 1.1 (8.5.97)"
#define TIME	"17:44:10"
#define PRGNAME	"hscpitt"
#define BASENAME	"HSCPITT"
#define VSTR	"hscpitt 1.1 (8.5.97)"
