/* C headerfile generated by RevUp 1.4 */

#define VERSION		1
#define REVISION	0
#define DATE	"4.12.96"
#define VERS	"hscpitt 1.0"
#define VSTRING	"hscpitt 1.0 (4.12.96)\r\n"
#define VERSTAG	"\0$VER: hscpitt 1.0 (4.12.96)"
#define TIME	"02:39:49"
#define PRGNAME	"hscpitt"
#define BASENAME	"HSCPITT"
#define VSTR	"hscpitt 1.0 (4.12.96)"
#define USER	"Thomas.Aglassinger"
#define HOST	"giga.or.at"
